"""
Create a stacked plot of chosen variables against PNBI (neutral beam injeciton power).  
"""
import pandas as pd
from matplotlib import pyplot as plt

df = pd.read_csv('varying_npart_1000-to-100000.csv')  # Dataset generated by main.py
df.sort_values('npart', ignore_index=True)
ydatas = ['runtime','damp','noise_level','omega',]          # list of y-variables to include in stacked plot.
xdata = df['npart']

# Create stacked plot with shared x-axis ('pnbi')
fig, ax = plt.subplots(len(ydatas), sharex=True)    

# Iterate through chosen y-variables and plot on a separate axis each
for i, var in enumerate(ydatas):
    ydata = df[var]
    ax[i].plot(xdata,ydata,label='Data')
    ax[i].set_ylabel(var)

    try:
        yerr = df[f'{var}_std']
        ax[i].fill_between(xdata,ydata-yerr,ydata+yerr, alpha=0.2, label='Error') # Plot error as shaded region 
    except:
        print("No error")
    if var=='damp':
        ax[i].axhline(-0.153, color = "black", ls="--", label="Analytical Result")
    elif var=='omega':
        ax[i].axhline(1.413, color = "black", ls="--", label="Analytical Result")


ax[0].set_title('Parameters vs Number of Particles')
ax[-1].set_xlabel('Number of Particles')
plt.legend()
plt.subplots_adjust(hspace=0)
plt.show()