"""
Create a stacked plot of chosen variables against PNBI (neutral beam injeciton power).  
"""
import pandas as pd
from matplotlib import pyplot as plt

df = pd.read_csv('variations_ncells_10-to-200.csv')  # Dataset generated by main.py
ydatas = ['runtime','damp','noise_level','omega',]          # list of y-variables to include in stacked plot.
xdata = df['ncells']

# Create stacked plot with shared x-axis ('pnbi')
fig, ax = plt.subplots(len(ydatas), sharex=True)    

# Iterate through chosen y-variables and plot on a separate axis each
for i, var in enumerate(ydatas):
    ydata = df[var]
    # yerr = df[f'{var}_std']
    # ax[i].fill_between(xdata,ydata-yerr,ydata+yerr, alpha=0.2, label='Standard Deviation') # Plot error as shaded region 
    ax[i].plot(xdata,ydata,)
    ax[i].set_ylabel(var)
    
ax[0].set_title('Parameters vs Number of Cells')
ax[-1].set_xlabel('Number of Cells')
plt.legend()
plt.subplots_adjust(hspace=0)
plt.show()